/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atmel_Maxtouch_MaxtouchJni */

#ifndef _Included_com_atmel_Maxtouch_MaxtouchJni
#define _Included_com_atmel_Maxtouch_MaxtouchJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    Initialise
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_Initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    GetSysfsDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_GetSysfsDirectory
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    GetDebugMessages
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_GetDebugMessages
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    ReadRegister
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_ReadRegister
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    WriteRegister
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_WriteRegister
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    SetDebugEnable
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_SetDebugEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    GetDebugEnable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_GetDebugEnable
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    SetPause
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_SetPause
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    GetPause
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_GetPause
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    LoadConfigFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_LoadConfigFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    BackupConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_BackupConfig
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    ResetChip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_ResetChip
  (JNIEnv *, jobject);

/*
 * Class:     com_atmel_Maxtouch_MaxtouchJni
 * Method:    CalibrateChip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atmel_Maxtouch_MaxtouchJni_CalibrateChip
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
